version: "3.8"

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: local.Dockerfile
    restart: 'no'
    networks:
      - mynet
    ports:
      - 5000:5000
    # nodemon watcher needs to watch for local changes to reload the app
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro

  database:
    container_name: database
    image: mongo:3.6.0
    restart: 'no'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - mynet
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

networks:
  mynet:
    driver: bridge

volumes:
  db: